server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|mp3|json)$ {
        expires off;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
